---
ignore:
  - conftest.py
  - htmlcov/*
  - nowplaying/vendor/*
  - nowplaying/version.py
  - NowPlaying.spec
  - build/*
  - template-src/vendor/*
  - nowplaying/template/vendor/*
  - site/*
  - keep/*

rule_settings:
  python_version: '3.10'
  disable:
    - assign-if-exp
    - no-conditionals-in-tests
    # Skip complex logic simplifications that reduce readability
    - de-morgan
    - merge-nested-ifs
    - simplify-boolean-logic
    - merge-duplicate-conditions
    - swap-if-else-branches
    - merge-elif
