[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]

[tool.vendoring]
destination = "nowplaying/vendor"
requirements = "vendor.txt"
namespace = "nowplaying.vendor"

[tool.pytest.ini_options]

# initializing qtbot _after_ asyncio or threading just
# breaks pytest horribily so force those tests first
testpaths = [
    "tests-qt",
    "tests"
]
markers = [
    "seratosettings: custom settings for serato ",
    "templatesettings: custom settings for templates",
]
qt_api = "pyside6"
log_cli = true
addopts = [
  "--cov=nowplaying",
  "--cov-config=.coveragerc",
  "--cov-report=html",
  "-ra",
]
log_level = "DEBUG"
asyncio_mode = "strict"
qt_qapp_name = "testsuite"

[tool.pylint.main]
# List of plugins (as comma separated values of python module names) to load,
# usually to register additional checkers.
load-plugins = [ "pylint.extensions.no_self_use" ]
ignore = [ "nowplaying/beam" ]
