---
template_families:
  mtv_style:
    base: websocket-base
    description: "MTV-style layouts with customizable fade effects"
    common_css:
      - obs-compatibility
      - kabel-font
      - mtv-layout
    common_websocket:
      - metadata-streaming

    templates:
      ws-mtv-cover-nofade:
        title: "Titlecard"
        description: "MTV Style with Cover - No Fade"
        body_layout: mtv-cover-layout
        display_js: mtv-display-cover
        effects: []

      ws-mtv-cover-fade:
        title: "Titlecard"
        description: "MTV Style with Cover - Fade Effects"
        body_layout: mtv-cover-layout
        display_js: mtv-display-cover
        effects: [fade-effects]

      ws-mtv-nofade:
        title: "Titlecard"
        description: "MTV Style Text Only - No Fade"
        body_layout: mtv-text-layout
        display_js: mtv-display-text
        effects: []

      ws-mtv-fade:
        title: "Titlecard"
        description: "MTV Style Text Only - Fade Effects"
        body_layout: mtv-text-layout
        display_js: mtv-display-text
        effects: [fade-effects]
