---
name: website-test

# Test that documentation builds successfully on all pushes
on: [push]  # yamllint disable-line rule:truthy


jobs:
  test_docs_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Test docs build
        run: properdocs build -f properdocs.yml --strict
