---
# yamllint disable rule:line-length
name: website-test

# Test that documentation builds successfully on all pushes
on: [push]  # yamllint disable-line rule:truthy


jobs:
  test_docs_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Test docs build
        run: properdocs build -f properdocs.yml --strict
