#
#
# yamllint disable rule:line-length
---
name: website

# execute this workflow automatically when a we push to master
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]

permissions:
  deployments: write

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:

      - name: Prereqs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get update
          apt-get install -y git python3-pip
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          chown -R $(id -u):$(id -g) "${PWD}"
        shell: bash

      # - name: check
      #   run: |
      #     pip3 install .

      - name: Execute script to build our documentation and update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WRITE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./build-website.sh"
        shell: bash
