---
name: Deploy MkDocs Documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: ['*.*.*']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Deploy documentation
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              # Stable release (e.g., 5.0.0) - deploy as latest
              mike deploy --push --update-aliases $VERSION latest
              mike set-default --push latest
            else
              # Preview/pre-release (e.g., 5.0.0-preview1) - deploy version only
              mike deploy --push $VERSION
            fi
          else
            mike deploy --push dev
          fi
