# yamllint disable rule:line-length
---
name: Static Linting

on: [push]  # yamllint disable-line rule:truthy

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          path: src
          fetch-depth: 0
      - name: test-patch
        uses: effectivemachines/yetus-test-patch-action@2e6a0da0efc8fcfb7cddbdcf4cc33dbbf536caf1  # main
        with:
          basedir: ./src
          patchdir: ./out
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
          plugins: 'all,-asflicense,-author,-findbugs,-gitlab,-jira,-jshint,-shelldocs'
      - name: Artifact output
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7
        with:
          name: apacheyetustestpatchactionout
          path: ${{ github.workspace }}/out
