# yamllint disable rule:line-length
---
name: Static Linting

on: [push]  # yamllint disable-line rule:truthy

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          path: src
          fetch-depth: 0
      - name: test-patch
        uses: effectivemachines/yetus-test-patch-action@c451fe551988d3304d7b322df093ec905563af49  # main
        with:
          basedir: ./src
          patchdir: ./out
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
          plugins: 'all,-asflicense,-author,-findbugs,-gitlab,-jira,-jshint,-shelldocs'
      - name: Artifact output
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7
        with:
          name: apacheyetustestpatchactionout
          path: ${{ github.workspace }}/out
